### ISSUE TITLE
fnc import fails with `./xml.py` in filepath

### ISSUE THREAD

**Issue by nikonikoniko** [dgilland/fnc#1]
to replicate:

```
fnc_bug/
  test.py
  xml.py (empty)
```

```
# test.py

from fnc import (
  compose
)
```

```
→ python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from fnc import (
  File "/usr/lib/python3.7/site-packages/fnc/__init__.py", line 244, in <module>
    from .__version__ import __version__
  File "/usr/lib/python3.7/site-packages/fnc/__version__.py", line 4, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib/python3.7/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
ModuleNotFoundError: No module named 'xml.parsers'; 'xml' is not a package
```

moving the xml file into a subfolder works.

importing libraries other than `fnc` works.

--------------------------------
using arch linux (btw) and python 3

fnc version: 0.4.0

**Comment by dgilland** [comment]
This is due to the local `xml.py` module shadowing something from the standard library.

A similar thing happens if you did something like:

```
foobar/
    test.py
    urllib3.py
```

```python
# test.py
import requests
```

```
$ python test.py
Traceback (most recent call last):
  File "test2.py", line 1, in <module>
    import requests
  File "/Users/dgilland/.virtualenvs/sandbox/lib/python3.7/site-packages/requests/__init__.py", line 46, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/Users/dgilland/.virtualenvs/sandbox/lib/python3.7/site-packages/requests/exceptions.py", line 9, in <module>
    from urllib3.exceptions import HTTPError as BaseHTTPError
ModuleNotFoundError: No module named 'urllib3.exceptions'; 'urllib3' is not a package
```

This is how the Python import system works so the "fix" is to not have a local top-level module that shadows some other module that's trying to be imported from site-packages or the standard library.

**Comment by nikonikoniko** [comment]
Thank you
